spring:
  cloud:
    gateway:
      routes:
        - id: contract-review-user-service
          uri: lb://contract-review--user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/login
        - id: review-contract-review-service
          uri: lb://review-contract--review-service
          predicates:
            - Path=/api/review-service/**  # 匹配的 WebSocket 路径
          filters:
            - name: TokenValidate
#
#        - id: index12306-ticket-service
#          uri: lb://index12306-ticket${unique-name:}-service/api/ticket-service/**
#          predicates:
#            - Path=/api/ticket-service/**
#          filters:
#            - name: TokenValidate
#              args:
#                blackPathPre:
#                  - /api/ticket-service/ticket/purchase
#                  - /api/ticket-service/ticket/pay/query
#                  - /api/ticket-service/ticket/cancel
#
#        - id: index12306-pay-service
#          uri: lb://index12306-pay${unique-name:}-service/api/pay-service/**
#          predicates:
#            - Path=/api/pay-service/**
#
#        - id: index12306-order-service
#          uri: lb://index12306-order${unique-name:}-service/api/order-service/**
#          predicates:
#            - Path=/api/order-service/**
#          filters:
#            - name: TokenValidate
#              args:
#                blackPathPre:
#                  - /api/order-service/order/ticket/query
#                  - /api/order-service/order/ticket/page
#                  - /api/order-service/order/ticket/self/page
